name: seon_plugin
description: SEON Anti Fraud Flutter Plugin - The Device Fingerprint tool collects thorough insight about the devices associated to a user.
version: 3.1.0
homepage: https://github.com/Drafteame/seon-flutter-sdk

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: io.draftea.seon_plugin
        pluginClass: SeonPlugin
      ios:
        pluginClass: SeonPlugin